# Generated by Django 3.2.3 on 2021-06-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'product review', 'verbose_name_plural': 'product reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], default=5, verbose_name='product rate'),
        ),
    ]
