# Generated by Django 3.2.3 on 2021-06-08 17:57

import django.core.validators
from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210608_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(help_text='a positive integer', validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[product.validators.positive_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(help_text='255 characters or fever', max_length=255, verbose_name='a product title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='letters, hyphens, numbers and underscores', max_length=255),
        ),
    ]
