# Generated by Django 3.2.3 on 2021-06-08 17:57

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10, validators=[product.validators.positive_validator]),
        ),
    ]
