# Generated by Django 3.2.3 on 2021-06-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
